export const LOGOUT = "LOGOUT";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const UPDATE_FAVORITE_MOVIES = "UPDATE_FAVORITE_MOVIES";
export const UPDATE_WATCHLIST = "UPDATE_WATCHLIST";
export const FETCH_SUCCESS_AUTH = "FETCH_SUCCESS_AUTH";